name: 'article-webpage-to-markdown-action'
description: "Automatically generate Markdown files based on the webpages of articles. Currently supports freeCodeCamp's news site."
author: 'freeCodeCamp-China'
inputs:
  newsLink:
    description: 'A string in a specific format that contains a link to a article.'
    required: true
  includeSelector:
    description: 'CSS selector of elements which should be included'
  ignoreSelector:
    description: 'CSS selector of elements which should be ignored'
  markDownFilePath:
    description: 'Path of the generated MarkDown file and relative path relative to the root folder.'
    required: false
    default: './'
  githubToken:
    description: ' GitHub  write and read token,auto create,no need to set'
    default: ''
  # This flag is used to skip the check of whether the article has been generated
  skipSameArticleCheck:
    description: 'Skip the check of whether the article has been generated'
    type: 'boolean'
    default: 'false'
  # This flag is used to skip the issue comment
  skipIssueComment:
    description: 'Skip issue comment'
    type: 'boolean'
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'

outputs:
  markdown_file_path:
    description: 'The path to the generated Markdown file.'
